#+title: dotfiles

[[file:20200418155222_information_technology.org][R:@information technology]]


* What are dotfiles?

Lets start with some definitions and descriptions

Dotfiles are files which contains application configuration, settings or preferences. Some dotfiles are edited with a text editor, while some are modified directly in the applications that they serve.

Dotfiles usually starts with a period (.) or are with a folder starting with a period, this is where they take their name.

* Dotfiles location conventions

The long time tradition is that dotfiles are stored directly in your home folder (~/). This was quite ok in the old days when you were running couple of apps, but nowadays, this is totally unrealistic. In my system only, I count several thousands of settings files. Most applications nowadays stores their dotfiles under ~/.config.

Appears that the ~/.config is part of the freedesktop.org [[https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html][XDG Base Directory Specification]] under the $XDG_CONFIG_HOME variable. By default, the specs specifies ~/.config. This is rarely changed (never seen it different).

In your own system, you'll find core utilities dotfiles sitting directly under your home folder, while most applications dotfiles will be under a subfolder of ~/.config.


* ways to manage dotfiles

This is where dotfiles management is useful (there is an extensive [[https://dotfiles.github.io/][github page]] around dotfiles, management tools, and practices).

i've used:
 1. started by just zipping them and emailing them around. it helped me for a while
 2. Then put them in a git repo. and manually creating symlinks
 3. Moved to yadm management tool with a bare repo, but did not stick with it. Bare git repos could be risky if you are not cautious. Also could not find out how to manage sensitive configuration files
 4. Back to basic git repo with stow using symlinks. This worked well, but still hard to manage sensitive files.
 5. Replaced stow with makefiles, and envsubst scripts to implement templating. This worked well, but tedious to maintain. Also, if I modified the destination, I would have to remember to integrate the changes also in my git repository.
 6. Now using [[https://www.chezmoi.io/][chezmoi]]

* chezmoi

** Installing chezmoi

[[https://www.chezmoi.io/docs/install/][Install | chezmoi.io]]

on Arch:
#+BEGIN_SRC bash
pacman -S chezmoi
#+END_SRC
** Getting help
Example:
#+BEGIN_SRC bash :results output :exports both
chezmoi help help
#+END_SRC

The reference documentation is extensive: [[https://www.chezmoi.io/docs/reference/][documentation]]

** Get started
If you look at the [[https://www.chezmoi.io/docs/quick-start/][quickstart]], you'll find that all you need to start is:

#+BEGIN_SRC bash
chezmoi init
#+END_SRC

then you can add managed files using the /add/ command.

Now lets take ~/.bashrc

#+BEGIN_SRC bash
chezmoi add ~/.bashrc
#+END_SRC

This will create a copy if this file under the chezmoi storage folder /~/.local/share/chezmoi/

You can also use the -r option to add files recursively:
#+BEGIN_SRC bash
chezmoi add -r ~/.config/newsboat
#+END_SRC

** Configuration file

The chezmoi configuration file is optional and located in the ~/.config/chezmoi/chezmoi.toml

You can specify the merge tool used by the merge command like here for meld:

#+BEGIN_SRC toml
[merge]
  command = "meld"
#+END_SRC

** storage location

You can /cd/ to the chezmoi storage folder

#+BEGIN_SRC bash
chezmoi cd
#+END_SRC

Here you can do any file operations you want.

Note that file names contains encoding for permissions and have a specific meaning for chezmoi.

** Managed files

From the moment you add a file to chezmoi, it gets copied to the chezmoi local directory and it becomes "managed".

You can find the list of managed files with the command:
#+BEGIN_SRC bash :results output
chezmoi managed
#+END_SRC

#+RESULTS:
#+begin_example
/home/benoit/.bashrc
#+end_example


** version control

Now that we have a file managed, the next thing you may want to do is to version control your dotfiles.

All you need to do is to go to the chezmoi storage folder and initialize the repository.

For git, it would be:

#+BEGIN_SRC bash
chezmoi cd
git init
git add .
git commit -m "initial commit with my bash configuration"
#+END_SRC

Chezmoi also has a git command:

#+BEGIN_SRC bash
chezmoi git init
chezmoi git add .
chezmoi git commit -m "initial commit with my bash configuration"
#+END_SRC

** Making changes to managed files

Any changes made outside of chezmoi's folder will be lost by default.

The best way to edit files is to edit files using chezmoi.

There are really two ways:
 1. call the /edit/ command, like /chezmoi edit ~/.bashrc/
    This command use the EDITOR environment variable to launch your favorite text editor
 2. navigate to the chezmoi's folder and edit them directly there

** Apply changes to managed files

The apply command can install any changes made to managed files on their target (ie: where they are used).

For example, if we changed the ~/.bashrc managed file using the /chezmoi edit ~/.bashrc/ command, we can install the new version using the command:

#+BEGIN_SRC bash :results output
chezmoi -v apply
#+END_SRC

*Note*: changes made to the targets are overwritten by the /apply/ command.

If you are unclear what changes will be applied, ensure you use the /--dry-run/ or /-n/ option:

#+BEGIN_SRC bash :results output
chezmoi -v -n apply
#+END_SRC

What you can also do is call edit with the -a command to apply after editing. You may also like the -d and -p together with -a to diff and confirm apply.

#+BEGIN_SRC bash
chezmoi edit -a -d -p ~/.bashrc
#+END_SRC


** Updating from remote changes

Here I usually just cd and run git commands.

You can also use the chezmoi update commands which pull changes from git remote and optionally apply changes.

You have choices here.

** Integrate changes made to the target files outside of chezmoi :ATTACH:
:PROPERTIES:
:ID:       f287420e-994a-45df-93fc-7f0fd79d0a9b
:END:

#+BEGIN_SRC bash
chezmoi merge ~/.bashrc
#+END_SRC

configure mergetool:

#+BEGIN_SRC toml
[merge]
  command = "meld"
#+END_SRC

Can also be vimdiff, p4merge, kdiff3, ediff emacs

** Templates

Variables in configuration files:
#+BEGIN_SRC toml
[data]
  email="myemail@athome.com"
#+END_SRC

And we add our bashrc file with the autotemplate feature:
#+BEGIN_SRC bash
# -T for template
# -a for auto
chezmoi add -T -a ~/.bashrc
#+END_SRC

the resulting template stored in chezmoi would be:
#+BEGIN_SRC bash
export EMAIL="{{ .email }}"
#+END_SRC

The /{{ .something }}/ gives you access to values within your configuration file that will be replaced during the /apply/ command execution.

You can see a list of pre-defined variables [[https://www.chezmoi.io/docs/reference/#template-variables][here]].

** Secrets

Sources for templates can be the configuration file or secret storage tools like bitwarden, gpg, keypassXC, pass, and many more.

See the page [[https://www.chezmoi.io/docs/how-to/#keep-data-private][keep data private]] for more details.


** Scripts

If you create scripts starting with /run_/ or /run_once_/, chezmoi will run them at every /apply/ or /once/ unless changed.

For install software, it's better to create /run_once_/ scripts.


** What else

The items above are the ones I plan to use the most. But chezmoi has much more to offer and the [[https://www.chezmoi.io/docs/reference/][documentation]] on it's website is quite good.
