#+TITLE: single responsibility principle

#+REVEAL_TRANS: none
#+REVEAL_THEME: moon
#+REVEAL_HLEVEL: 3
#+OPTIONS: toc:nil

related :: [[file:20200228101727_programming.org][R:programming]]

* What is it?

The first letter in SOLID

* Robert C. Martin


#+BEGIN_QUOTE
A class should have only one reason to change
#+END_QUOTE

/defined in the 90s by Robert C. Martin/

* More precisely

#+BEGIN_QUOTE
every module or class should have responsibility over a single part of the
functionality provided by the software, and that responsibility should be
entirely encapsulated by the class, module or function.
#+END_QUOTE

* Roots

Principle with roots in:
1. High Cohesion software (by Tom DeMarco as early as 1979)
2. Separation of concerns (by Meilir Page-Jones in 1988)

* Example

#+BEGIN_SRC java :noeval

class Employee {
    String id;
    String name;

    Money calculatePay() {};
    void printInfo() {};
    void save() {};

}

#+END_SRC

* Examples
1. Print with calculation
2. A module/class/method or switch case you keep changing over time for various reasons.
3. persistence code with logic
4. logic with reporting
5. perf measurements within logic classes

* Misuse / understanding
1. Reason to change is quite vague
2. If misunderstood, could end up with tons of really really small classes.

* How to detect?
1. Reviews
2. Static code analysis
   1. smells
   2. git history

* Detect files with most commits

In an effort to try to find "hot" spots in my repos, I wrote this script:

#+BEGIN_SRC shell :noeval

find . -type f \
    | grep -v .git \
    | while read f
      do
          echo $(git log --follow --oneline -- "$f"| wc -l) $f;
      done \
    | sort -n -r \
    | head -20

#+END_SRC

A better script would rate result based on the date intervals between first and
last commit.

* References

1. [[https://en.wikipedia.org/wiki/Single_responsibility_principle][Single responsibility principle - Wikipedia]]
2. [[https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html][Clean Coder Blog]] - Uncle Bob
3. [[https://hackernoon.com/you-dont-understand-the-single-responsibility-principle-abfdd005b137][Think you understand the Single Responsibility Principle?]]
