#+TITLE: assertions

[[file:20200511092514-java.org][R:java]] [[file:20200228101727_programming.org][R:programming]]

* assertj
Fluent assertion library

assertion uses equals / hashcode methods to assert, but uses toString to render assertion errors.

This offers nice diff in IDEs

** TODO enhancements

*** better string representations

its possible to override the string representation of objects.

* hamcrest - alternative to assertj

really popular alternative is hamcrest (larger userbase)

quite similar to assertj with extensive list of assertions, at the same time different as it follows junit assertions instead of being fluent.

#+BEGIN_SRC java
assertThat(something, isEquals(anotherThing));
#+END_SRC

does not provide fluent assertions

* Equals and Hashcode assertions
Assert any equals method meet requirements using:
https://jqno.nl/equalsverifier/

* JSONAssert
Assert required information within a JSON payload.

http://jsonassert.skyscreamer.org/

Here is an example:
#+BEGIN_SRC java
JSONObject data = getRESTData("/friends/367.json");
String expected = "{friends:[{id:123,name:\"Corby Page\"},{id:456,name:\"Carter Page\"}]}";
JSONAssert.assertEquals(expected, data, false);
#+END_SRC

* JSONSchema validation

* test architecture
:PROPERTIES:
:ID:       f6109c15-c60d-4d1f-967b-06f886b7305e
:END:

https://archunit.org

cool tool to test various architecture elements like:
1. dependencies
2. model
3. use of lumbok
