* Coding practices
** code quality - how to improve team quality production
*** static analysis
| Type         | tools          |
|--------------+----------------|
| Style        | Checkstyle     |
| Correctness  | Findbugs, PMD  |
| Architecture | Sonar          |
| Duplication  | PMD/CPD, Sonar |

** code quality - cleancode

clean code manifesto: [http://manifesto.softwarecraftsmanship.org/]

*** code quality
	-- there are no compiler warnings. only error or invisible
	-- 1 hour every 2 day for project annoyance
	- Feature branch is bad: http://martinfowler.com/bliki/FeatureBranch.html
*** stories
	-- bad merge? curly brace error: http://www.dwheeler.com/essays/apple-goto-fail.html
	-- 16bits vs 32bits: http://itsfoss.com/a-floating-point-error-that-caused-a-damage-worth-half-a-billion/
	-- bad deployment: https://dougseven.com/2014/04/17/knightmare-a-devops-cautionary-tale/
	-- Testivus: http://pantras.free.fr/articles/testivus.html)

*** clean code best practices
**** naming
***** class 
ref: http://stackoverflow.com/questions/1866794/naming-classes-how-to-avoid-calling-everything-a-whatevermanager
****** DO:
  	   - Shepherd
       - Bucket/Pool
       - Repository
       - Superviser
       - Coordinator
       - Builder
       - Writer
       - Reader
       - Handler
       - Container
       - Protocol
       - Target
       - Converter
       - Controller
       - View
       - Factory
       - Entity
****** Dont: 
       - Service
       - manager
       - Helper
       - Utility
       - Object


**** naming
***** class
	- DO: 
		- Shepherd
		- Bucket/Pool
		- Repository
		- Superviser
		- Coordinator
		- Builder
		- Writer
		- Reader
		- Handler
		- Container
		- Protocol
		- Target
		- Converter
		- Controller
		- View
		- Factory
		- Entity
	- Dont: Service, manager, Helper, Utility, Object

ref: http://stackoverflow.com/questions/1866794/naming-classes-how-to-avoid-calling-everything-a-whatevermanager

** Testing
*** the way of the Testivus

- If you write code, write tests.
- Don’t get stuck on unit testing dogma.
- Embrace unit testing karma.
- Think of code and test as one.
- The test is more important than the unit.
- The best time to test is when the code is fresh.
- Tests not run waste away.
- An imperfect test today is better than a perfect test someday.
- An ugly test is better than no test.
- Sometimes, the test justifies the means.
- Only fools use no tools.
- Good tests fail.

*** Testivus on Test Coverage

Early one morning, a programmer asked the great master:

“I am ready to write some unit tests. What code coverage should I aim for?”
The great master replied:

“Don’t worry about coverage, just write some good tests.”
The programmer smiled, bowed, and left.

...

Later that day, a second programmer asked the same question.

The great master pointed at a pot of boiling water and said:

“How many grains of rice should put in that pot?”
The programmer, looking puzzled, replied:

“How can I possibly tell you? It depends on how many people you need to feed, how hungry they are, what other food you are serving, how much rice you have available, and so on.”
“Exactly,” said the great master.

The second programmer smiled, bowed, and left.

...

Toward the end of the day, a third programmer came and asked the same question about code coverage.

“Eighty percent and no less!” Replied the master in a stern voice, pounding his fist on the table.
The third programmer smiled, bowed, and left.

...

After this last reply, a young apprentice approached the great master:

“Great master, today I overheard you answer the same question about code coverage with three different answers. Why?”
The great master stood up from his chair:

“Come get some fresh tea with me and let’s talk about it.”
After they filled their cups with smoking hot green tea, the great master began to answer:

“The first programmer is new and just getting started with testing. Right now he has a lot of code and no tests. He has a long way to go; focusing on code coverage at this time would be depressing and quite useless. He’s better off just getting used to writing and running some tests. He can worry about coverage later.”

“The second programmer, on the other hand, is quite experience both at programming and testing. When I replied by asking her how many grains of rice I should put in a pot, I helped her realize that the amount of testing necessary depends on a number of factors, and she knows those factors better than I do – it’s her code after all. There is no single, simple, answer, and she’s smart enough to handle the truth and work with that.”

“I see,” said the young apprentice, “but if there is no single simple answer, then why did you answer the third programmer ‘Eighty percent and no less’?”

The great master laughed so hard and loud that his belly, evidence that he drank more than just green tea, flopped up and down.

“The third programmer wants only simple answers – even when there are no simple answers … and then does not follow them anyway.”
The young apprentice and the grizzled great master finished drinking their tea in contemplative silence.

** Bad code
*** example 1

#+BEGIN_SRC java
private static int INITIAL = 1;
private static int THING1 = 2;
private static int THING2 = 3;
private static int THING3 = 4;

void next(int state) {
	switch (state) {
	case INITIAL:
	doThing1();
	break;
	case THING1:
	doThing2();
	break;
	case THING2:
	doThing3();
	break;
	case THING3:
	// do nothing -- exit
	break;
	}
}

void doThing1() {
	// Do "thing 1"
	next(THING1);
}

void doThing2() {
	// Do "thing 2"
	next(THING2);
}

void doThing3() {
	// Do "thing 3"
	next(THING3);
}
#+END_SRC

*** example 2

#+BEGIN_SRC java
Session session = Session.getDefaultInstance(props, null);
if (debug)
	session.setDebug(true);
#+END_SRC

*** example 3

#+BEGIN_SRC java
BufferedReader reader = new BufferedReader( new FileReader (file));
String line = null;
String text = "";

while( ( line = reader.readLine() ) != null ) {
    text = text + line;
}
#+END_SRC

*** example 4

#+BEGIN_SRC java
package mrpd.mrr;

/**
 * This class creates a data base connection using JDBC driver.
 * The created connection will be used and re-used subsequently
 * in different classes of the MRR application.
 *
 * The "Singleton pattern" is used to create a static object 
 * and return a reference upon request
 *
 * Creation date: (2/22/2001 10:15:04 AM)
 * @author: XXXX XXXX
*/

import java.sql.*;
import java.util.*;

public class DBConnection  {

	private static DBConnection dbCon = new DBConnection();
	private static String errCode="0000";
	private Connection connection;

private DBConnection() {

	 /**This is the constructor of class of DBConnection.
	  *The function is to make a database connection.
	  *
	  *Define local variables 	
	  */

	String sDriver, sPassword, sUserID, sURL;

	//Specify Driver name, user ID and password 
	String driver = "COM.ibm.db2.jdbc.app.DB2Driver";
	String userid = "mrpd1";
	String password = "XXXXXXX";

	//specify database URL
	String url=null;
	url	= "jdbc:db2:mrpddb";  //MRPDDB on production
 //	url = "jdbc:db2:DEV"; // local development instance
 //	url	= "jdbc:db2:dhoneds"; //XXXX's local alias to MRPDDB on dhoneds
	System.out.println("Using database: " + url);	

	//Attempt to load the JDBC driver with newInstance
	try {
		Class.forName(driver).newInstance();
	} catch (Exception e) {
		System.err.println("Failed to load current driver.");
		errCode = "8301";
		return;
	}

	//Attempt to connect to the database
	try {
		connection = DriverManager.getConnection(url, userid, password);
		System.out.println("\n\tConnection to "+url+" successful\n");
	} catch (SQLException SQLe) {
		System.err.println("problems connecting to " + url + ":");
		System.err.println(SQLe.getMessage());
		System.err.println("SQL State: " + SQLe.getSQLState());
		if (connection != null) {
			try {
				connection.close();
			} catch (Exception e) {
			}
		}
		errCode = "8302";
		return;
	}
 }
 public static Connection getConnection() {	
	return dbCon.connection;
 }
 public static String getErrorCode() {	
	return errCode;
 }
 }
#+END_SRC

